### ISSUE TITLE
Wii Mailboxes

### ISSUE THREAD

**Issue by Fer3243** [RiiConnect24/RC24-Clear-Tool#1]
When trying to delete Wii Mailboxes, the program crashes and doesn't delete anything.
![image](https://user-images.githubusercontent.com/76263403/132108876-97f6d9d0-47da-4ef8-9e07-2f7bfb35bb6e.png)

**Comment by larsenv** [comment]
I got another report of that happening, and I'm not sure why it would be crashing...

**Comment by Peter0x44** [comment]
I tried to run addr2line on each of the addresses in the stack dump to see if I could figure out something more insightful about what is going wrong
```
[peter@PeterD RC24-Clear-Tool]$ /opt/devkitpro/devkitPPC/bin/powerpc-eabi-addr2line -e boot.elf 0x80036658
??:?
[peter@PeterD RC24-Clear-Tool]$ /opt/devkitpro/devkitPPC/bin/powerpc-eabi-addr2line -e boot.elf 0x80038c20
??:?
[peter@PeterD RC24-Clear-Tool]$ /opt/devkitpro/devkitPPC/bin/powerpc-eabi-addr2line -e boot.elf 0x800060d4
/home/peter/trash/RC24-Clear-Tool/source/main.c:52
[peter@PeterD RC24-Clear-Tool]$ /opt/devkitpro/devkitPPC/bin/powerpc-eabi-addr2line -e boot.elf 0x8001cd8c
/home/davem/projects/devkitpro/pacman-packages/libogc/src/libogc-2.3.1/libogc/lwp_watchdog.c:20
[peter@PeterD RC24-Clear-Tool]$ /opt/devkitpro/devkitPPC/bin/powerpc-eabi-addr2line -e boot.elf 0x8001cd38
/home/davem/projects/devkitpro/pacman-packages/libogc/src/libogc-2.3.1/libogc/lwp_wkspace.inl:6
```
The only one even in the source of the rc24 clear tool is this:
https://github.com/RiiConnect24/RC24-Clear-Tool/blob/338eaa4e277c39ced6094b198b72f8cea0ccfa5f/source/main.c#L52
which is literally printf, so I struggle to see how it could cause a crash
